services:
  # Backend Service (Development)
  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev  # Use development Dockerfile
    container_name: nurtura-backend-dev
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5001:5000"  # Map host port 5001 to container port 5000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - nurtura-dev-network

  # Frontend Service (Development - using Vite dev server)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nurtura-frontend-dev
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5001  # Point to development backend
    ports:
      - "3000:3000"
    depends_on:
      - backend-dev
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nurtura-dev-network
    command: npm run dev

networks:
  nurtura-dev-network:
    driver: bridge
