services:
  # Cypress E2E Testing Service
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    container_name: nurtura-cypress
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.ts:/app/cypress.config.ts
      - ./src:/app/src
    environment:
      - CYPRESS_baseUrl=http://frontend
      - CYPRESS_apiUrl=http://backend:5000
    depends_on:
      - frontend
      - backend
    networks:
      - nurtura-network
    command: npx cypress run

  # Test Database (Optional - for isolated testing)
  test-db:
    image: mongo:latest
    container_name: nurtura-test-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: nurtura-test
    ports:
      - "27018:27017"
    volumes:
      - test_mongodb_data:/data/db
    networks:
      - nurtura-network

networks:
  nurtura-network:
    external: true

volumes:
  test_mongodb_data:
