services:
  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nurtura-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
    networks:
      - nurtura-network
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nurtura-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - nurtura-network

networks:
  nurtura-network:
    driver: bridge
